"""Tests for image provenance (issue #38).

Verifies that:
1. images/SOURCES.md exists and documents the project
2. framework/image-manifest.csv has license + generator columns
3. Every image on disk is covered by the manifest
4. SOURCES.md and manifest agree on the source generator
"""
import csv
import re
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SOURCES_MD = PROJECT_ROOT / "images" / "SOURCES.md"
MANIFEST = PROJECT_ROOT / "framework" / "image-manifest.csv"


class TestSourcesDoc:
    """images/SOURCES.md exists and is well-formed."""

    def test_sources_md_exists(self):
        assert SOURCES_MD.exists(), "images/SOURCES.md missing"

    def test_sources_md_documents_generator(self):
        content = SOURCES_MD.read_text(encoding="utf-8")
        assert "Gemini" in content or "Google Gemini" in content, \
            "SOURCES.md does not document the generator"

    def test_sources_md_documents_license(self):
        content = SOURCES_MD.read_text(encoding="utf-8")
        assert "MIT" in content, "SOURCES.md does not document the license"

    def test_sources_md_documents_date(self):
        content = SOURCES_MD.read_text(encoding="utf-8")
        # 2026-08 (or similar YYYY-MM)
        assert re.search(r"20\d{2}-\d{2}", content), \
            "SOURCES.md does not document a generation date"

    def test_sources_md_has_audit_checklist(self):
        content = SOURCES_MD.read_text(encoding="utf-8")
        assert "checklist" in content.lower() or "- [ ]" in content, \
            "SOURCES.md missing audit checklist"

    def test_sources_md_states_no_third_party(self):
        """The file should explicitly state that no third-party images are bundled."""
        content = SOURCES_MD.read_text(encoding="utf-8")
        # Look for explicit "None" or "no third-party" claim
        assert re.search(r"(?i)(none|no third-party|no third party)", content), \
            "SOURCES.md should explicitly state third-party status"


class TestManifestSchema:
    """framework/image-manifest.csv has the columns required by issue #38."""

    @pytest.fixture(scope="class")
    def manifest(self):
        if not MANIFEST.exists():
            pytest.skip("image-manifest.csv missing")
        return list(csv.DictReader(MANIFEST.open(encoding="utf-8")))

    @pytest.fixture(scope="class")
    def fields(self):
        if not MANIFEST.exists():
            pytest.skip("image-manifest.csv missing")
        return csv.DictReader(MANIFEST.open(encoding="utf-8")).fieldnames

    def test_manifest_has_license_column(self, fields):
        assert "license" in fields, "image-manifest.csv missing 'license' column"

    def test_manifest_has_generator_column(self, fields):
        assert "generator" in fields, "image-manifest.csv missing 'generator' column"

    def test_manifest_has_generation_date_column(self, fields):
        assert "generation_date" in fields, \
            "image-manifest.csv missing 'generation_date' column"

    def test_manifest_license_values_are_mit(self, manifest):
        """All current images are MIT-licensed."""
        for row in manifest:
            assert row.get("license") == "MIT", \
                f"Row {row['filename']} has license={row.get('license')!r} (expected MIT)"

    def test_manifest_generator_values_consistent(self, manifest):
        """All current images were generated by Gemini."""
        for row in manifest:
            gen = row.get("generator", "")
            assert "Gemini" in gen, \
                f"Row {row['filename']} has generator={gen!r} (expected Gemini)"


class TestManifestCoversDisk:
    """Every image on disk is in the manifest."""

    def test_every_disk_image_in_manifest(self):
        if not MANIFEST.exists():
            pytest.skip("image-manifest.csv missing")
        # The manifest's 'filename' column already includes the subdirectory
        # (e.g. 'phonograms/all-single.png' not 'all-single.png').
        manifest_filenames = set()
        with MANIFEST.open(encoding="utf-8", newline="") as f:
            for row in csv.DictReader(f):
                manifest_filenames.add(row["filename"])
        images_dir = PROJECT_ROOT / "images"
        on_disk = set()
        for path in images_dir.rglob("*.png"):
            rel = path.relative_to(images_dir).as_posix()
            on_disk.add(rel)
        missing = on_disk - manifest_filenames
        # SOURCES.md is allowed to exist but not be a PNG
        missing.discard("SOURCES.md")
        assert not missing, (
            f"Images on disk but missing from manifest: {sorted(missing)}"
        )
