"""Helper for stamping the build version into generated MD files (issue #24).

Every generator under scripts/ calls `stamp(content)` before writing its
output to disk. The stamp is a single-line HTML comment that is invisible
in the rendered PDF (HTML comments are dropped by WeasyPrint) but visible
in source so a `grep -L "OpenPhonograms v"` can flag stale files.

Read VERSION at import time so all writes in a single generator run
share the same stamp even if VERSION is bumped mid-run.
"""
from pathlib import Path

from version import get_version

VERSION_STAMP = f"<!-- generated by OpenPhonograms v{get_version()} -->\n"


def stamp(content: str) -> str:
    """Prepend the version stamp to a string of MD content.

    Idempotent: if the file already carries a stamp (any version), it's
    replaced in-place so re-running a generator doesn't accumulate
    comment lines.
    """
    # Strip any prior stamp (current or legacy shape) before prepending.
    lines = content.splitlines()
    out = []
    for line in lines:
        if line.startswith("<!-- generated by OpenPhonograms v") and line.endswith("-->"):
            continue
        out.append(line)
    body = "\n".join(out)
    # Preserve trailing newline behavior of input.
    if body and not body.endswith("\n"):
        body += "\n"
    return VERSION_STAMP + body


if __name__ == "__main__":
    print(VERSION_STAMP)