#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Jeremy Morris. Released under the MIT License (see LICENSE).
"""One-shot migration: emit data/*.yaml from current Python constants.

Idempotent. Reads:
  - framework/phonograms.py (SINGLE/MULTI/MULTI3/MULTI4/PG_STAGE)
  - framework/rules.py (RULES/RULE_STAGE)
  - scripts/generate-stage1.py (PHONOGRAMS — Stage-1 writing/group/examples)
  - scripts/generate-game-data.py (_SENTENCES)

Emits:
  - data/phonograms.yaml (with Stage-1 fields merged from generate-stage1.py)
  - data/rules.yaml
  - data/sentences.yaml
  - data/{silent_e,roots,high_frequency_words,decodable_wordlists}.yaml (stubs)

Run once on main; commit output. Do NOT re-run after Slices 1-8 land —
YAML becomes canonical and constants will be deleted in Slice 9.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"


def _load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    ph = _load_module("phonograms", ROOT / "framework" / "phonograms.py")
    rl = _load_module("rules", ROOT / "framework" / "rules.py")

    # Load Stage-1 PHONOGRAMS via AST parsing (no exec side-effects).
    # We import the module via importlib for the constants, then read
    # its PHONOGRAMS dict via a controlled exec scope.
    stage1 = _load_module("gen_stage1", ROOT / "scripts" / "generate-stage1.py")
    stage1_pgs: dict[str, dict[str, Any]] = stage1.PHONOGRAMS

    # Merge: canonical from framework/phonograms.py + Stage-1 extras.
    pg_entries: list[dict[str, Any]] = []
    for pg_id, data in {**ph.SINGLE, **ph.MULTI, **ph.MULTI3, **ph.MULTI4}.items():
        kind = (
            "single" if pg_id in ph.SINGLE
            else "multi" if pg_id in ph.MULTI
            else "multi3" if pg_id in ph.MULTI3
            else "multi4"
        )
        stage = ph.PG_STAGE[pg_id]
        entry: dict[str, Any] = {
            "id": pg_id,
            "stage": stage,
            "kind": kind,
            "sounds": data["sounds"],
            "words": list(data["words"]),
        }
        if pg_id in stage1_pgs:
            s1 = stage1_pgs[pg_id]
            entry["vowel"] = s1["vowel"]
            entry["sound_count"] = s1["sound_count"]
            entry["examples"] = [{"sound": e[0], "words": e[1]} for e in s1["examples"]]
            entry["writing"] = s1["writing"]
            entry["group"] = s1["group"]
            if "rule" in s1:
                entry["rule"] = s1["rule"]
        pg_entries.append(entry)

    pg_entries.sort(key=lambda e: (e["stage"], e["id"]))

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "phonograms.yaml").write_text(
        "# Auto-generated by scripts/migrate-data.py — do NOT edit by hand.\n"
        + yaml.safe_dump({"phonograms": pg_entries}, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )
    print(f"  OK   data/phonograms.yaml: {len(pg_entries)} entries")

    # Rules
    rule_entries = []
    for num, data in rl.RULES.items():
        rule_entries.append({
            "number": str(num),
            "stage": rl.RULE_STAGE[num],
            "name": data["name"],
            "words": list(data["words"]),
        })
    rule_entries.sort(key=lambda e: int(e["number"]))
    (DATA_DIR / "rules.yaml").write_text(
        "# Auto-generated by scripts/migrate-data.py — do NOT edit by hand.\n"
        + yaml.safe_dump({"rules": rule_entries}, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )
    print(f"  OK   data/rules.yaml: {len(rule_entries)} entries")

    # Sentences (read from generate-game-data.py::_SENTENCES)
    gd = _load_module("gen_game_data", ROOT / "scripts" / "generate-game-data.py")
    sents = sorted(
        ({"word": w, "sentence": s} for w, s in gd._SENTENCES.items()),
        key=lambda e: e["word"],
    )
    (DATA_DIR / "sentences.yaml").write_text(
        "# Auto-generated by scripts/migrate-data.py — do NOT edit by hand.\n"
        + yaml.safe_dump({"sentences": sents}, sort_keys=False, allow_unicode=True, width=100),
        encoding="utf-8",
    )
    print(f"  OK   data/sentences.yaml: {len(sents)} entries")

    print("Migration complete. data/*.yaml committed. Validate with: just validate-data")
    return 0


if __name__ == "__main__":
    sys.exit(main())
